#ifndef PRAGMA_GTLAYOUT_LIB_H
#define PRAGMA_GTLAYOUT_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
** Copyright 1993-1999 by Olaf 'Olsen' Barthel
** Changes in 47.2 by Costel 'Cyborg' Mincea
** This library is freely distributable.
** This is the first complete stand-alone release of the "gtlayout.library" user
** interface creation and management tool kit.
** I'm grateful for any enhancement requests, bug reports and especially bug
** fixes. Contact: olsen@sourcery.han.de
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_GTLAYOUT_PROTOS_H
#include <clib/gtlayout_protos.h>
#endif /* CLIB_GTLAYOUT_PROTOS_H */

/* "gtlayout.library" */
/*--- functions in V80 or higher --- */
#pragma amicall(GTLayoutBase, 0x1E, LT_LevelWidth(a0,a1,a2,d0,d1,a3,a5,d2))
#pragma amicall(GTLayoutBase, 0x24, LT_DeleteHandle(a0))
#pragma amicall(GTLayoutBase, 0x2A, LT_CreateHandle(a0,a1))
#pragma amicall(GTLayoutBase, 0x30, LT_CreateHandleTagList(a0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x30, LT_CreateHandleTags(a0,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x36, LT_Rebuild(a0,a1,a2,d0,d1))
#pragma amicall(GTLayoutBase, 0x3C, LT_HandleInput(a0,d0,a1,a2,a3))
#pragma amicall(GTLayoutBase, 0x42, LT_BeginRefresh(a0))
#pragma amicall(GTLayoutBase, 0x48, LT_EndRefresh(a0,d0))
#pragma amicall(GTLayoutBase, 0x4E, LT_GetAttributesA(a0,d0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x4E, LT_GetAttributes(a0,d0,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x54, LT_SetAttributesA(a0,d0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x54, LT_SetAttributes(a0,d0,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x5A, LT_AddA(a0,d0,d1,d2,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x5A, LT_Add(a0,d0,d1,d2,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x60, LT_NewA(a0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x60, LT_New(a0,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x66, LT_EndGroup(a0))
#pragma amicall(GTLayoutBase, 0x6C, LT_LayoutA(a0,a1,a2,d0,d1,d2,d3,a3))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x6C, LT_Layout(a0,a1,a2,d0,d1,d2,d3,a3))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x72, LT_LayoutMenusA(a0,a1,a2))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0x72, LT_LayoutMenus(a0,a1,a2))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0x8A, LT_LabelWidth(a0,a1))
#pragma amicall(GTLayoutBase, 0x90, LT_LabelChars(a0,a1))
#pragma amicall(GTLayoutBase, 0x96, LT_LockWindow(a0))
#pragma amicall(GTLayoutBase, 0x9C, LT_UnlockWindow(a0))
#pragma amicall(GTLayoutBase, 0xA2, LT_DeleteWindowLock(a0))
#pragma amicall(GTLayoutBase, 0xA8, LT_ShowWindow(a0,a1))
#pragma amicall(GTLayoutBase, 0xAE, LT_Activate(a0,d0))
#pragma amicall(GTLayoutBase, 0xB4, LT_PressButton(a0,d0))
#pragma amicall(GTLayoutBase, 0xBA, LT_GetCode(d0,d1,d2,a0))
/*--- functions in V878 or higher --- */
#pragma amicall(GTLayoutBase, 0xC0, LT_GetIMsg(a0))
#pragma amicall(GTLayoutBase, 0xC6, LT_ReplyIMsg(a0))
/*--- functions in V280 or higher --- */
#pragma amicall(GTLayoutBase, 0xCC, LT_BuildA(a0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0xCC, LT_Build(a0,a1))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0xD2, LT_RebuildTagList(a0,d0,a1))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0xD2, LT_RebuildTags(a0,d0,a1))
#endif /* __STORM__ */
/*--- functions in V880 or higher --- */
#pragma amicall(GTLayoutBase, 0xD8, LT_UpdateStrings(a0))
/*--- functions in V1080 or higher --- */
#pragma amicall(GTLayoutBase, 0xDE, LT_DisposeMenu(a0))
#pragma amicall(GTLayoutBase, 0xE4, LT_NewMenuTemplate(a0,a1,a2,a3,d0,d1))
#pragma amicall(GTLayoutBase, 0xEA, LT_NewMenuTagList(a0))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0xEA, LT_NewMenuTags(a0))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0xF0, LT_MenuControlTagList(a0,a1,a2))
#if defined(__STORM__)
#pragma tagcall(GTLayoutBase, 0xF0, LT_MenuControlTags(a0,a1,a2))
#endif /* __STORM__ */
#pragma amicall(GTLayoutBase, 0xF6, LT_GetMenuItem(a0,d0))
#pragma amicall(GTLayoutBase, 0xFC, LT_FindMenuCommand(a0,d0,d1,a1))
/*--- functions in V1380 or higher --- */
#pragma amicall(GTLayoutBase, 0x102, LT_NewLevelWidth(a0,a1,a2,d0,d1,a3,d3,d2))
/*--- functions in V3080 or higher --- */
#pragma amicall(GTLayoutBase, 0x108, LT_Refresh(a0))
/*--- functions in V3380 or higher --- */
#pragma amicall(GTLayoutBase, 0x10E, LT_CatchUpRefresh(a0))
/*--- functions in V3880 or higher --- */
#pragma amicall(GTLayoutBase, 0x114, LT_GetWindowUserData(a0,a1))
/*--- functions in V4680 or higher --- */
#pragma amicall(GTLayoutBase, 0x11A, LT_Redraw(a0,d0))

#endif /* PRAGMA_GTLAYOUT_LIB_H */
