#ifndef PRAGMAS_GTLAYOUT_PRAGMAS_H
#define PRAGMAS_GTLAYOUT_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
** Copyright 1993-1999 by Olaf 'Olsen' Barthel
** Changes in 47.2 by Costel 'Cyborg' Mincea
** This library is freely distributable.
** This is the first complete stand-alone release of the "gtlayout.library" user
** interface creation and management tool kit.
** I'm grateful for any enhancement requests, bug reports and especially bug
** fixes. Contact: olsen@sourcery.han.de
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_GTLAYOUT_PROTOS_H
#include <clib/gtlayout_protos.h>
#endif /* CLIB_GTLAYOUT_PROTOS_H */

/* "gtlayout.library" */
/*--- functions in V80 or higher --- */
#pragma libcall GTLayoutBase LT_LevelWidth 1E 2DB10A9808
#pragma libcall GTLayoutBase LT_DeleteHandle 24 801
#pragma libcall GTLayoutBase LT_CreateHandle 2A 9802
#pragma libcall GTLayoutBase LT_CreateHandleTagList 30 9802
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_CreateHandleTags 30 9802
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_Rebuild 36 10A9805
#pragma libcall GTLayoutBase LT_HandleInput 3C BA90805
#pragma libcall GTLayoutBase LT_BeginRefresh 42 801
#pragma libcall GTLayoutBase LT_EndRefresh 48 0802
#pragma libcall GTLayoutBase LT_GetAttributesA 4E 90803
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_GetAttributes 4E 90803
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_SetAttributesA 54 90803
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_SetAttributes 54 90803
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_AddA 5A 9210805
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_Add 5A 9210805
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_NewA 60 9802
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_New 60 9802
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_EndGroup 66 801
#pragma libcall GTLayoutBase LT_LayoutA 6C B3210A9808
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_Layout 6C B3210A9808
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_LayoutMenusA 72 A9803
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_LayoutMenus 72 A9803
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_LabelWidth 8A 9802
#pragma libcall GTLayoutBase LT_LabelChars 90 9802
#pragma libcall GTLayoutBase LT_LockWindow 96 801
#pragma libcall GTLayoutBase LT_UnlockWindow 9C 801
#pragma libcall GTLayoutBase LT_DeleteWindowLock A2 801
#pragma libcall GTLayoutBase LT_ShowWindow A8 9802
#pragma libcall GTLayoutBase LT_Activate AE 0802
#pragma libcall GTLayoutBase LT_PressButton B4 0802
#pragma libcall GTLayoutBase LT_GetCode BA 821004
/*--- functions in V878 or higher --- */
#pragma libcall GTLayoutBase LT_GetIMsg C0 801
#pragma libcall GTLayoutBase LT_ReplyIMsg C6 801
/*--- functions in V280 or higher --- */
#pragma libcall GTLayoutBase LT_BuildA CC 9802
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_Build CC 9802
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_RebuildTagList D2 90803
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_RebuildTags D2 90803
#endif /* __SASC_60 */
/*--- functions in V880 or higher --- */
#pragma libcall GTLayoutBase LT_UpdateStrings D8 801
/*--- functions in V1080 or higher --- */
#pragma libcall GTLayoutBase LT_DisposeMenu DE 801
#pragma libcall GTLayoutBase LT_NewMenuTemplate E4 10BA9806
#pragma libcall GTLayoutBase LT_NewMenuTagList EA 801
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_NewMenuTags EA 801
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_MenuControlTagList F0 A9803
#if defined(__SASC_60)
#pragma tagcall GTLayoutBase LT_MenuControlTags F0 A9803
#endif /* __SASC_60 */
#pragma libcall GTLayoutBase LT_GetMenuItem F6 0802
#pragma libcall GTLayoutBase LT_FindMenuCommand FC 910804
/*--- functions in V1380 or higher --- */
#pragma libcall GTLayoutBase LT_NewLevelWidth 102 23B10A9808
/*--- functions in V3080 or higher --- */
#pragma libcall GTLayoutBase LT_Refresh 108 801
/*--- functions in V3380 or higher --- */
#pragma libcall GTLayoutBase LT_CatchUpRefresh 10E 801
/*--- functions in V3880 or higher --- */
#pragma libcall GTLayoutBase LT_GetWindowUserData 114 9802
/*--- functions in V4680 or higher --- */
#pragma libcall GTLayoutBase LT_Redraw 11A 0802

#endif /* PRAGMAS_GTLAYOUT_PRAGMAS_H */
