#ifndef CLIB_GTLAYOUT_PROTOS_H
#define CLIB_GTLAYOUT_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
** Copyright 1993-1999 by Olaf 'Olsen' Barthel
** Changes in 47.2 by Costel 'Cyborg' Mincea
** This library is freely distributable.
** This is the first complete stand-alone release of the "gtlayout.library" user
** interface creation and management tool kit.
** I'm grateful for any enhancement requests, bug reports and especially bug
** fixes. Contact: olsen@sourcery.han.de
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif

/* "gtlayout.library"*/
/*--- functions in V80 or higher ---*/
void LT_LevelWidth(struct LayoutHandle *handle, STRPTR levelFormat, APTR dispFunc, LONG min, LONG max, LONG *maxWidth, LONG *maxLen, LONG fullCheck);
void LT_DeleteHandle(struct LayoutHandle *handle);
struct LayoutHandle *LT_CreateHandle(struct Screen *screen, struct TextAttr *font);
struct LayoutHandle *LT_CreateHandleTagList(struct Screen *screen, struct TagItem *tagList);
struct LayoutHandle *LT_CreateHandleTags(struct Screen *screen, ...);
BOOL LT_Rebuild(struct LayoutHandle *handle, struct IBox *bounds, LONG extraWidth, LONG extraHeight, LONG clear);
void LT_HandleInput(struct LayoutHandle *handle, ULONG msgQualifier, ULONG *msgClass, UWORD *msgCode, struct Gadget **msgGadget);
void LT_BeginRefresh(struct LayoutHandle *handle);
void LT_EndRefresh(struct LayoutHandle *handle, LONG complete);
LONG LT_GetAttributesA(struct LayoutHandle *handle, LONG id, struct TagItem *tagList);
LONG LT_GetAttributes(struct LayoutHandle *handle, LONG id, ...);
void LT_SetAttributesA(struct LayoutHandle *handle, LONG id, struct TagItem *tagList);
void LT_SetAttributes(struct LayoutHandle *handle, LONG id, ...);
void LT_AddA(struct LayoutHandle *handle, LONG type, STRPTR label, LONG id, struct TagItem *tagList);
void LT_Add(struct LayoutHandle *handle, LONG type, STRPTR label, LONG id, ...);
void LT_NewA(struct LayoutHandle *handle, struct TagItem *tagList);
void LT_New(struct LayoutHandle *handle, ...);
void LT_EndGroup(struct LayoutHandle *handle);
struct Window *LT_LayoutA(struct LayoutHandle *handle, STRPTR title, struct IBox *bounds, LONG extraWidth, LONG extraHeight, ULONG idcmp, LONG align, struct TagItem *tagParams);
struct Window *LT_Layout(struct LayoutHandle *handle, STRPTR title, struct IBox *bounds, LONG extraWidth, LONG extraHeight, ULONG idcmp, LONG align, ...);
struct Menu *LT_LayoutMenusA(struct LayoutHandle *handle, struct NewMenu *menuTemplate, struct TagItem *tagParams);
struct Menu *LT_LayoutMenus(struct LayoutHandle *handle, struct NewMenu *menuTemplate, ...);
LONG LT_LabelWidth(struct LayoutHandle *handle, STRPTR label);
LONG LT_LabelChars(struct LayoutHandle *handle, STRPTR label);
void LT_LockWindow(struct Window *window);
void LT_UnlockWindow(struct Window *window);
void LT_DeleteWindowLock(struct Window *window);
void LT_ShowWindow(struct LayoutHandle *handle, LONG activate);
void LT_Activate(struct LayoutHandle *handle, LONG id);
BOOL LT_PressButton(struct LayoutHandle *handle, LONG id);
LONG LT_GetCode(ULONG msgQualifier, ULONG msgClass, ULONG msgCode, struct Gadget *msgGadget);
/*--- functions in V878 or higher ---*/
struct IntuiMessage *LT_GetIMsg(struct LayoutHandle *handle);
void LT_ReplyIMsg(struct IntuiMessage *msg);
/*--- functions in V280 or higher ---*/
struct Window *LT_BuildA(struct LayoutHandle *handle, struct TagItem *tagParams);
struct Window *LT_Build(struct LayoutHandle *handle, ...);
BOOL LT_RebuildTagList(struct LayoutHandle *handle, LONG clear, struct TagItem *tags);
BOOL LT_RebuildTags(struct LayoutHandle *handle, LONG clear, ...);
/*--- functions in V880 or higher ---*/
void LT_UpdateStrings(struct LayoutHandle *handle);
/*--- functions in V1080 or higher ---*/
void LT_DisposeMenu(struct Menu *menu);
struct Menu *LT_NewMenuTemplate(struct Screen *screen, struct TextAttr *textAttr, struct Image *amigaGlyph, struct Image *checkGlyph, LONG *error, struct NewMenu *menuTemplate);
struct Menu *LT_NewMenuTagList(struct TagItem *tagList);
struct Menu *LT_NewMenuTags(...);
void LT_MenuControlTagList(struct Window *window, struct Menu *intuitionMenu, struct TagItem *tags);
void LT_MenuControlTags(struct Window *window, struct Menu *intuitionMenu, ...);
struct MenuItem *LT_GetMenuItem(struct Menu *menu, ULONG id);
struct MenuItem *LT_FindMenuCommand(struct Menu *menu, ULONG msgCode, ULONG msgQualifier, struct Gadget *msgGadget);
/*--- functions in V1380 or higher ---*/
void LT_NewLevelWidth(struct LayoutHandle *handle, STRPTR levelFormat, APTR dispFunc, LONG min, LONG max, LONG *maxWidth, LONG *maxLen, LONG fullCheck);
/*--- functions in V3080 or higher ---*/
void LT_Refresh(struct LayoutHandle *handle);
/*--- functions in V3380 or higher ---*/
void LT_CatchUpRefresh(struct LayoutHandle *handle);
/*--- functions in V3880 or higher ---*/
APTR LT_GetWindowUserData(struct Window *window, APTR defaultValue);
/*--- functions in V4680 or higher ---*/
void LT_Redraw(struct LayoutHandle *handle, LONG id);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_GTLAYOUT_PROTOS_H */
