#ifndef PROTO_GTLAYOUT_H
#define PROTO_GTLAYOUT_H

/*
** 'C' prototype and compiler specific header file combo
**
** Copyright 1993-1999 by Olaf 'Olsen' Barthel
** Changes in 47.2 by Costel 'Cyborg' Mincea
** This library is freely distributable.
** This is the first complete stand-alone release of the "gtlayout.library" user
** interface creation and management tool kit.
** I'm grateful for any enhancement requests, bug reports and especially bug
** fixes. Contact: olsen@sourcery.han.de
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/gtlayout_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * GTLayoutBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_GTLAYOUT_PRAGMAS_H
#include <pragmas/gtlayout_pragmas.h>
#endif /* PRAGMAS_GTLAYOUT_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_GTLAYOUT_LIB_H
#include <pragma/gtlayout_lib.h>
#endif /* PRAGMA_GTLAYOUT_LIB_H */

#elif defined(__VBCC__)

#include <clib/gtlayout_protos.h>

#ifndef INLINE_GTLAYOUT_PROTOS_H
#include <inline/gtlayout_protos.h>
#endif /* INLINE_GTLAYOUT_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_GTLAYOUT_H
#include <inline/gtlayout.h>
#endif /* INLINE_GTLAYOUT_H */
#else
#include <clib/gtlayout_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/gtlayout_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_GTLAYOUT_H */
