#ifndef INLINE_GTLAYOUT_PROTOS_H
#define INLINE_GTLAYOUT_PROTOS_H

/*
** VBCC format inline files.
**
** Copyright 1993-1999 by Olaf 'Olsen' Barthel
** Changes in 47.2 by Costel 'Cyborg' Mincea
** This library is freely distributable.
** This is the first complete stand-alone release of the "gtlayout.library" user
** interface creation and management tool kit.
** I'm grateful for any enhancement requests, bug reports and especially bug
** fixes. Contact: olsen@sourcery.han.de
**
** Generated by LibDescConverter from an sfd file
*/

/* "gtlayout.library" */
/*--- functions in V80 or higher --- */
void __LT_LevelWidth(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR levelFormat, __reg("a2") APTR dispFunc, __reg("d0") LONG min, __reg("d1") LONG max, __reg("a3") LONG *maxWidth, __reg("a5") LONG *maxLen, __reg("d2") LONG fullCheck)="\tjsr\t-30(a6)";
#define LT_LevelWidth(handle, levelFormat, dispFunc, min, max, maxWidth, maxLen, fullCheck) __LT_LevelWidth(GTLayoutBase, (handle), (levelFormat), (dispFunc), (min), (max), (maxWidth), (maxLen), (fullCheck))

void __LT_DeleteHandle(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-36(a6)";
#define LT_DeleteHandle(handle) __LT_DeleteHandle(GTLayoutBase, (handle))

struct LayoutHandle *__LT_CreateHandle(__reg("a6") void *, __reg("a0") struct Screen *screen, __reg("a1") struct TextAttr *font)="\tjsr\t-42(a6)";
#define LT_CreateHandle(screen, font) __LT_CreateHandle(GTLayoutBase, (screen), (font))

struct LayoutHandle *__LT_CreateHandleTagList(__reg("a6") void *, __reg("a0") struct Screen *screen, __reg("a1") struct TagItem *tagList)="\tjsr\t-48(a6)";
#define LT_CreateHandleTagList(screen, tagList) __LT_CreateHandleTagList(GTLayoutBase, (screen), (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct LayoutHandle *__LT_CreateHandleTags(__reg("a6") void *, __reg("a0") struct Screen *screen, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-48(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_CreateHandleTags(...) __LT_CreateHandleTags(GTLayoutBase, __VA_ARGS__)
#endif

BOOL __LT_Rebuild(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") struct IBox *bounds, __reg("a2") LONG extraWidth, __reg("d0") LONG extraHeight, __reg("d1") LONG clear)="\tjsr\t-54(a6)";
#define LT_Rebuild(handle, bounds, extraWidth, extraHeight, clear) __LT_Rebuild(GTLayoutBase, (handle), (bounds), (extraWidth), (extraHeight), (clear))

void __LT_HandleInput(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") ULONG msgQualifier, __reg("a1") ULONG *msgClass, __reg("a2") UWORD *msgCode, __reg("a3") struct Gadget **msgGadget)="\tjsr\t-60(a6)";
#define LT_HandleInput(handle, msgQualifier, msgClass, msgCode, msgGadget) __LT_HandleInput(GTLayoutBase, (handle), (msgQualifier), (msgClass), (msgCode), (msgGadget))

void __LT_BeginRefresh(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-66(a6)";
#define LT_BeginRefresh(handle) __LT_BeginRefresh(GTLayoutBase, (handle))

void __LT_EndRefresh(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG complete)="\tjsr\t-72(a6)";
#define LT_EndRefresh(handle, complete) __LT_EndRefresh(GTLayoutBase, (handle), (complete))

LONG __LT_GetAttributesA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id, __reg("a1") struct TagItem *tagList)="\tjsr\t-78(a6)";
#define LT_GetAttributesA(handle, id, tagList) __LT_GetAttributesA(GTLayoutBase, (handle), (id), (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __LT_GetAttributes(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-78(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_GetAttributes(...) __LT_GetAttributes(GTLayoutBase, __VA_ARGS__)
#endif

void __LT_SetAttributesA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id, __reg("a1") struct TagItem *tagList)="\tjsr\t-84(a6)";
#define LT_SetAttributesA(handle, id, tagList) __LT_SetAttributesA(GTLayoutBase, (handle), (id), (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
void __LT_SetAttributes(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-84(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_SetAttributes(...) __LT_SetAttributes(GTLayoutBase, __VA_ARGS__)
#endif

void __LT_AddA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG type, __reg("d1") STRPTR label, __reg("d2") LONG id, __reg("a1") struct TagItem *tagList)="\tjsr\t-90(a6)";
#define LT_AddA(handle, type, label, id, tagList) __LT_AddA(GTLayoutBase, (handle), (type), (label), (id), (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
void __LT_Add(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG type, __reg("d1") STRPTR label, __reg("d2") LONG id, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-90(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_Add(...) __LT_Add(GTLayoutBase, __VA_ARGS__)
#endif

void __LT_NewA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") struct TagItem *tagList)="\tjsr\t-96(a6)";
#define LT_NewA(handle, tagList) __LT_NewA(GTLayoutBase, (handle), (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
void __LT_New(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-96(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_New(...) __LT_New(GTLayoutBase, __VA_ARGS__)
#endif

void __LT_EndGroup(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-102(a6)";
#define LT_EndGroup(handle) __LT_EndGroup(GTLayoutBase, (handle))

struct Window *__LT_LayoutA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR title, __reg("a2") struct IBox *bounds, __reg("d0") LONG extraWidth, __reg("d1") LONG extraHeight, __reg("d2") ULONG idcmp, __reg("d3") LONG align, __reg("a3") struct TagItem *tagParams)="\tjsr\t-108(a6)";
#define LT_LayoutA(handle, title, bounds, extraWidth, extraHeight, idcmp, align, tagParams) __LT_LayoutA(GTLayoutBase, (handle), (title), (bounds), (extraWidth), (extraHeight), (idcmp), (align), (tagParams))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct Window *__LT_Layout(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR title, __reg("a2") struct IBox *bounds, __reg("d0") LONG extraWidth, __reg("d1") LONG extraHeight, __reg("d2") ULONG idcmp, __reg("d3") LONG align, ...)="\tmove.l\ta3,-(a7)\n\tlea\t4(a7),a3\n\tjsr\t-108(a6)\n\tmovea.l\t(a7)+,a3";
#define LT_Layout(...) __LT_Layout(GTLayoutBase, __VA_ARGS__)
#endif

struct Menu *__LT_LayoutMenusA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") struct NewMenu *menuTemplate, __reg("a2") struct TagItem *tagParams)="\tjsr\t-114(a6)";
#define LT_LayoutMenusA(handle, menuTemplate, tagParams) __LT_LayoutMenusA(GTLayoutBase, (handle), (menuTemplate), (tagParams))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct Menu *__LT_LayoutMenus(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") struct NewMenu *menuTemplate, ...)="\tmove.l\ta2,-(a7)\n\tlea\t4(a7),a2\n\tjsr\t-114(a6)\n\tmovea.l\t(a7)+,a2";
#define LT_LayoutMenus(...) __LT_LayoutMenus(GTLayoutBase, __VA_ARGS__)
#endif

LONG __LT_LabelWidth(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR label)="\tjsr\t-138(a6)";
#define LT_LabelWidth(handle, label) __LT_LabelWidth(GTLayoutBase, (handle), (label))

LONG __LT_LabelChars(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR label)="\tjsr\t-144(a6)";
#define LT_LabelChars(handle, label) __LT_LabelChars(GTLayoutBase, (handle), (label))

void __LT_LockWindow(__reg("a6") void *, __reg("a0") struct Window *window)="\tjsr\t-150(a6)";
#define LT_LockWindow(window) __LT_LockWindow(GTLayoutBase, (window))

void __LT_UnlockWindow(__reg("a6") void *, __reg("a0") struct Window *window)="\tjsr\t-156(a6)";
#define LT_UnlockWindow(window) __LT_UnlockWindow(GTLayoutBase, (window))

void __LT_DeleteWindowLock(__reg("a6") void *, __reg("a0") struct Window *window)="\tjsr\t-162(a6)";
#define LT_DeleteWindowLock(window) __LT_DeleteWindowLock(GTLayoutBase, (window))

void __LT_ShowWindow(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") LONG activate)="\tjsr\t-168(a6)";
#define LT_ShowWindow(handle, activate) __LT_ShowWindow(GTLayoutBase, (handle), (activate))

void __LT_Activate(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id)="\tjsr\t-174(a6)";
#define LT_Activate(handle, id) __LT_Activate(GTLayoutBase, (handle), (id))

BOOL __LT_PressButton(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id)="\tjsr\t-180(a6)";
#define LT_PressButton(handle, id) __LT_PressButton(GTLayoutBase, (handle), (id))

LONG __LT_GetCode(__reg("a6") void *, __reg("d0") ULONG msgQualifier, __reg("d1") ULONG msgClass, __reg("d2") ULONG msgCode, __reg("a0") struct Gadget *msgGadget)="\tjsr\t-186(a6)";
#define LT_GetCode(msgQualifier, msgClass, msgCode, msgGadget) __LT_GetCode(GTLayoutBase, (msgQualifier), (msgClass), (msgCode), (msgGadget))

/*--- functions in V878 or higher --- */
struct IntuiMessage *__LT_GetIMsg(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-192(a6)";
#define LT_GetIMsg(handle) __LT_GetIMsg(GTLayoutBase, (handle))

void __LT_ReplyIMsg(__reg("a6") void *, __reg("a0") struct IntuiMessage *msg)="\tjsr\t-198(a6)";
#define LT_ReplyIMsg(msg) __LT_ReplyIMsg(GTLayoutBase, (msg))

/*--- functions in V280 or higher --- */
struct Window *__LT_BuildA(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") struct TagItem *tagParams)="\tjsr\t-204(a6)";
#define LT_BuildA(handle, tagParams) __LT_BuildA(GTLayoutBase, (handle), (tagParams))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct Window *__LT_Build(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-204(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_Build(...) __LT_Build(GTLayoutBase, __VA_ARGS__)
#endif

BOOL __LT_RebuildTagList(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG clear, __reg("a1") struct TagItem *tags)="\tjsr\t-210(a6)";
#define LT_RebuildTagList(handle, clear, tags) __LT_RebuildTagList(GTLayoutBase, (handle), (clear), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
BOOL __LT_RebuildTags(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG clear, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-210(a6)\n\tmovea.l\t(a7)+,a1";
#define LT_RebuildTags(...) __LT_RebuildTags(GTLayoutBase, __VA_ARGS__)
#endif

/*--- functions in V880 or higher --- */
void __LT_UpdateStrings(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-216(a6)";
#define LT_UpdateStrings(handle) __LT_UpdateStrings(GTLayoutBase, (handle))

/*--- functions in V1080 or higher --- */
void __LT_DisposeMenu(__reg("a6") void *, __reg("a0") struct Menu *menu)="\tjsr\t-222(a6)";
#define LT_DisposeMenu(menu) __LT_DisposeMenu(GTLayoutBase, (menu))

struct Menu *__LT_NewMenuTemplate(__reg("a6") void *, __reg("a0") struct Screen *screen, __reg("a1") struct TextAttr *textAttr, __reg("a2") struct Image *amigaGlyph, __reg("a3") struct Image *checkGlyph, __reg("d0") LONG *error, __reg("d1") struct NewMenu *menuTemplate)="\tjsr\t-228(a6)";
#define LT_NewMenuTemplate(screen, textAttr, amigaGlyph, checkGlyph, error, menuTemplate) __LT_NewMenuTemplate(GTLayoutBase, (screen), (textAttr), (amigaGlyph), (checkGlyph), (error), (menuTemplate))

struct Menu *__LT_NewMenuTagList(__reg("a6") void *, __reg("a0") struct TagItem *tagList)="\tjsr\t-234(a6)";
#define LT_NewMenuTagList(tagList) __LT_NewMenuTagList(GTLayoutBase, (tagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct Menu *__LT_NewMenuTags(__reg("a6") void *, ...)="\tmove.l\ta0,-(a7)\n\tlea\t4(a7),a0\n\tjsr\t-234(a6)\n\tmovea.l\t(a7)+,a0";
#define LT_NewMenuTags(...) __LT_NewMenuTags(GTLayoutBase, __VA_ARGS__)
#endif

void __LT_MenuControlTagList(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct Menu *intuitionMenu, __reg("a2") struct TagItem *tags)="\tjsr\t-240(a6)";
#define LT_MenuControlTagList(window, intuitionMenu, tags) __LT_MenuControlTagList(GTLayoutBase, (window), (intuitionMenu), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
void __LT_MenuControlTags(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct Menu *intuitionMenu, ...)="\tmove.l\ta2,-(a7)\n\tlea\t4(a7),a2\n\tjsr\t-240(a6)\n\tmovea.l\t(a7)+,a2";
#define LT_MenuControlTags(...) __LT_MenuControlTags(GTLayoutBase, __VA_ARGS__)
#endif

struct MenuItem *__LT_GetMenuItem(__reg("a6") void *, __reg("a0") struct Menu *menu, __reg("d0") ULONG id)="\tjsr\t-246(a6)";
#define LT_GetMenuItem(menu, id) __LT_GetMenuItem(GTLayoutBase, (menu), (id))

struct MenuItem *__LT_FindMenuCommand(__reg("a6") void *, __reg("a0") struct Menu *menu, __reg("d0") ULONG msgCode, __reg("d1") ULONG msgQualifier, __reg("a1") struct Gadget *msgGadget)="\tjsr\t-252(a6)";
#define LT_FindMenuCommand(menu, msgCode, msgQualifier, msgGadget) __LT_FindMenuCommand(GTLayoutBase, (menu), (msgCode), (msgQualifier), (msgGadget))

/*--- functions in V1380 or higher --- */
void __LT_NewLevelWidth(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("a1") STRPTR levelFormat, __reg("a2") APTR dispFunc, __reg("d0") LONG min, __reg("d1") LONG max, __reg("a3") LONG *maxWidth, __reg("d3") LONG *maxLen, __reg("d2") LONG fullCheck)="\tjsr\t-258(a6)";
#define LT_NewLevelWidth(handle, levelFormat, dispFunc, min, max, maxWidth, maxLen, fullCheck) __LT_NewLevelWidth(GTLayoutBase, (handle), (levelFormat), (dispFunc), (min), (max), (maxWidth), (maxLen), (fullCheck))

/*--- functions in V3080 or higher --- */
void __LT_Refresh(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-264(a6)";
#define LT_Refresh(handle) __LT_Refresh(GTLayoutBase, (handle))

/*--- functions in V3380 or higher --- */
void __LT_CatchUpRefresh(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle)="\tjsr\t-270(a6)";
#define LT_CatchUpRefresh(handle) __LT_CatchUpRefresh(GTLayoutBase, (handle))

/*--- functions in V3880 or higher --- */
APTR __LT_GetWindowUserData(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") APTR defaultValue)="\tjsr\t-276(a6)";
#define LT_GetWindowUserData(window, defaultValue) __LT_GetWindowUserData(GTLayoutBase, (window), (defaultValue))

/*--- functions in V4680 or higher --- */
void __LT_Redraw(__reg("a6") void *, __reg("a0") struct LayoutHandle *handle, __reg("d0") LONG id)="\tjsr\t-282(a6)";
#define LT_Redraw(handle, id) __LT_Redraw(GTLayoutBase, (handle), (id))


#endif /* INLINE_GTLAYOUT_PROTOS_H */
